# Generated by Django 5.0.14 on 2026-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('MXN', 'MXN ($)'), ('ARS', 'ARS ($)'), ('BRL', 'BRL (R$)'), ('CLP', 'CLP ($)'), ('COP', 'COP ($)')], default='USD', max_length=3),
        ),
    ]
